
const cards=[
['flatland','Flatland Roofing & Insulation','Roofing & insulation company · USA','A U.S. home-services company providing residential and commercial roofing, insulation and related property services.','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/FLATLAND%20HOME%20PAGE.webp',['Service Business','UX/UI','Responsive']],
['soheir','Soheir Farag Swimming Academy','Ladies-only swimming academy · Egypt','A ladies-only swimming academy offering training programs, products and information to an English and Arabic-speaking audience.','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/SOHEIR%20FARAG%20EN.webp',['Framer','Arabic RTL','Responsive']],
['tretrip','TreTrip','Travel services company · KSA','A travel company offering organized trips, pilgrimage programs, accommodations, events, shipping and bookable travel experiences.','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/TRETRIP%20HOMEPAGE.webp',['Travel','Booking','Responsive']],
['dalton','Town of Dalton','Municipal website · Massachusetts, USA','A local government website serving residents of Dalton, Massachusetts with town services, news, meetings, resources and essential public information.','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/DALTON.webp',['UX/UI','Accessibility','Responsive']],
['townweb','Town Web','GovTech company · USA','A GovTech company providing municipal websites and digital tools that help local governments serve residents and manage everyday work.','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/TOWN%20WEB1.webp',['GovTech','Art Direction','ICP Focus']]
];
const cases={
dalton:{name:'Town of Dalton',status:'In development · Municipal web design',intro:'Dalton came to the project with a document describing what the town wanted its new website to include. From that starting point, I shaped the homepage experience, visual direction, responsive behavior and the design decisions that would carry through development.',notes:[['The challenge','A municipal website has to work for a very broad audience. Residents may arrive looking for a meeting, a form, a department, a notice or one specific public service, so the interface has to make information feel easy to reach rather than bureaucratic.'],['Accessibility from day one','ADA accessibility was part of the design logic from the first concept through developer handoff. For U.S. public websites, accessibility is a legal and practical requirement. I avoided interactions whose meaning depends on color or color changes alone, and considered contrast, sizing, navigation clarity and predictable interaction patterns throughout.'],['My role','I owned the visual direction, UX/UI design, responsive states, accessibility decisions and developer handoff. The site is currently in development.']],quote:'Accessibility was part of the design logic, not a checklist added at the end.',images:[['Desktop homepage','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/DALTON.webp'],['Mobile design','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/DALTON%20MOBILE.webp','mobile']]},
soheir:{name:'Soheir Farag Swimming Academy',status:'Live · End to end',intro:'This project started before there was even a client brief. I knew the academy, designed a homepage concept based on what I understood about the business and sent the owner a working staging link. She loved it. We met, discussed what the academy actually needed online, and that first idea became a complete live website.',notes:[['100% ownership','I found the client, initiated the project, recommended the site structure, communicated directly with the owner, designed every page, built it in Framer, handled hosting and launched it. I still maintain the website.'],['A brand that fits the business','The academy is ladies-only, so the visual direction needed to feel feminine without becoming childish. Blue connects naturally to pools and water, while clean layouts and sporty imagery keep the experience modern, active and credible. Testimonials, products and academy information all live inside the same visual system.'],['Bilingual by design','The site has English and Arabic versions, with the Arabic experience designed as true RTL. Navigation, alignment and composition respond to reading direction rather than treating Arabic as translated text pasted into an English layout.']],quote:'I did not wait for a brief. I showed the client a vision first, then turned it into the real business website.',images:[['English homepage','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/SOHEIR%20FARAG%20EN.webp'],['Arabic RTL homepage','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/SOHEIR%20FARAG%20ARABIC.webp']],live:'https://www.soheirfarag.com/'},
tretrip:{name:'TreTrip',status:'Live · Travel platform',intro:'TreTrip was more complex than a typical travel-agency website because the business itself covered several different service types. Trips and pilgrimage programs needed booking journeys, while accommodations, events, shipping and other services still had to make sense inside one coherent website.',notes:[['The problem','The client had a document describing what they wanted, but the business categories and user journeys were not fully resolved. A major part of the design work was translating those thoughts into a hierarchy people could understand quickly.'],['From discovery to booking','I designed the project from start to finish, including the homepage, service structure, internal service pages, program detail experiences and booking flows. The goal was to let the company feel broad without making the interface feel complicated.'],['An itinerary you can explore','One of my favorite ideas was the interactive program map. Hovering over a map pin reveals a photo and information about the place the traveler will visit. On touch devices, the same information can appear through a tap-triggered popup, preserving the idea without relying on hover.']],quote:'The map turns an itinerary from a list of place names into a preview of the trip itself.',images:[['Homepage','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/TRETRIP%20HOMEPAGE.webp'],['Program details and booking experience','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/TRETRIP%20INTERNAL%20PAGE.webp']],live:'https://www.tretrip.com/'},
flatland:{name:'Flatland Roofing & Insulation',status:'UX process · Service business',intro:'For Flatland, the starting material was unusually lean: the client gave me the names of the pages they wanted. I had to turn that into an actual website system, deciding what belonged where, how the services connected and what each page needed to accomplish.',notes:[['Information architecture','I proposed the sitemap and organized roofing, insulation, commercial services and supporting content into a structure the client could review before we moved into detailed page design.'],['Wireframes before polish','I presented wireframes for internal pages so we could agree on hierarchy, content flow and conversion points before visual styling entered the conversation. The client approved the direction, then I translated that structure into final UI.'],['Business goals in the interface','The final experience balances service discovery, quote capture, financing, reviews and local credibility. The goal was conversion without turning every section into a competing call to action.']],quote:'Page names became an approved sitemap, wireframes and a complete conversion-focused website system.',images:[['Homepage','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/FLATLAND%20HOME%20PAGE.webp'],['Proposed sitemap','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/Flatland-sitemap%20%281%29-1.webp'],['Internal page wireframe','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/FLATLAND%20INTERNAL%20PAGE%20WIREFRAME.webp'],['Final internal page','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/FLATLAND%20INTERNAL%20PAGE.webp']]},
townweb:{name:'Town Web',status:'Self-initiated concept · Art direction',intro:'This was a self-initiated redesign direction for Town Web. Instead of approaching the homepage as a catalogue of municipal products, I built the concept around the person Town Web is actually trying to reach: municipal clerks.',notes:[['Designed for the ICP','The concept speaks to clerks through their actual work and problems, then introduces Town Web as a partner that makes those responsibilities easier. The messaging is clear, concise and deliberately non-overwhelming.'],['Making the ecosystem understandable','Town Web has multiple services and products. The design introduces them as connected solutions and focuses on why each one matters before asking the visitor to care about product terminology.'],['Art direction with a job to do','The brand colors, editorial illustration and playful composition are intentionally more expressive than a typical GovTech site. The visual storytelling prompts the visitor to keep scrolling while strong calls to action keep the commercial purpose clear. The concept and creative direction were entirely mine.']],quote:'The goal was not to make GovTech cute. It was to make it feel human, clear and relevant to the person actually using it.',images:[['Full proposed homepage concept','https://cdn.jsdelivr.net/gh/esraaki/Portfolio@main/TOWN%20WEB1.webp']]}}
const P=document.getElementById('projects');cards.forEach(c=>{let e=document.createElement('article');e.className='project';e.tabIndex=0;e.dataset.case=c[0];e.innerHTML=`<div class="visual"><img loading="lazy" decoding="async" src="${c[4]}" alt="${c[1]} website design"><span class="view">View case study</span></div><div class="copy"><div class="label">${c[2]}</div><h3>${c[1]}</h3><p>${c[3]}</p><div class="tags">${c[5].map(t=>`<span>${t}</span>`).join('')}</div></div>`;if(c[0]==='flatland'){let im=e.querySelector('img');im.loading='eager';im.fetchPriority='high'}P.appendChild(e)});
const M=document.getElementById('modal'),B=document.getElementById('case'),N=document.getElementById('modalName');function openCase(k){let c=cases[k];N.textContent=c.name;let notes=c.notes.map(n=>`<div class="note"><h4>${n[0]}</h4><p>${n[1]}</p></div>`).join('');let g=c.images.map((x,i)=>`<div><div class="cap">${x[0]}</div><div class="shot ${x[2]==='mobile'?'mobile-shot':''}"><img loading="lazy" decoding="async" fetchpriority="low" src="${x[1]}" alt="${c.name} ${x[0]}"></div>${i===0?`<div class="notes">${notes}</div><div class="quote">${c.quote}</div>`:''}</div>`).join('');B.innerHTML=`<div class="case-head"><div class="ey">${c.status}</div><h2>${c.name}</h2><p>${c.intro}</p></div><div class="gallery">${g}</div>${c.live?`<a class="live" href="${c.live}" target="_blank">View live website ↗</a>`:''}`;M.classList.add('open');document.body.classList.add('no-scroll');let first=B.querySelector('.gallery img');if(first){first.loading='eager';first.fetchPriority='high'}M.scrollTop=0}function shut(){M.classList.remove('open');document.body.classList.remove('no-scroll')}P.onclick=e=>{let x=e.target.closest('.project');if(x)openCase(x.dataset.case)};P.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){let x=e.target.closest('.project');if(x)openCase(x.dataset.case)}};document.getElementById('close').onclick=shut;
const W=[['clear.','#0071e3'],['useful.','#7c3aed'],['beautiful.','#d05a2a'],['memorable.','#198754']];let i=0,w=document.getElementById('word');w.style.color=W[0][1];setInterval(()=>{w.style.opacity=0;w.style.transform='translateY(5px)';setTimeout(()=>{i=(i+1)%W.length;w.textContent=W[i][0];w.style.color=W[i][1];w.style.opacity=1;w.style.transform='none'},110)},850);
const CV=document.getElementById('cvModal');function cvShut(){CV.classList.remove('open');if(!M.classList.contains('open'))document.body.classList.remove('no-scroll')}document.getElementById('cvBtn').onclick=()=>{CV.classList.add('open');document.body.classList.add('no-scroll')};document.getElementById('cvClose').onclick=cvShut;document.addEventListener('keydown',e=>{if(e.key==='Escape'){shut();cvShut()}});

const dl=document.getElementById('cvDownload');
if(dl)dl.onclick=e=>{e.preventDefault();const {jsPDF}=window.jspdf;const d=new jsPDF({unit:'pt',format:'a4'});let y=48,L=44,W=507;
const line=(t,sz=10,b=false,sp=13)=>{d.setFont('helvetica',b?'bold':'normal');d.setFontSize(sz);const r=d.splitTextToSize(t,W);d.text(r,L,y);y+=r.length*sp};
const sec=t=>{y+=10;line(t,11,true,14)};
const bullet=t=>{d.setFont('helvetica','normal');d.setFontSize(9.3);const r=d.splitTextToSize('• '+t,W-8);d.text(r,L+8,y);y+=r.length*11.2+3};
line('ESRAA SALAH',23,true,24);line('WEB DESIGNER',12,true,16);line('Egypt | esraasalah4242@gmail.com | +20 110 247 6011 | LinkedIn',9,false,11);line('Portfolio: esraa-salah-portfolio.vercel.app',9,false,11);
sec('EXPERIENCE');line('Web & Marketing Designer | Town Web | 2024 - Present',10.2,true,12);line('Wisconsin, USA',9,false,11);
bullet('Lead web design across 20+ client projects, translating business goals and complex requirements into responsive websites from information architecture and wireframes through final UI and developer handoff.');
bullet('Design accessible, information-rich websites for municipalities and public-sector organizations, balancing usability, visual identity, responsive behavior, and diverse audience needs.');
bullet('Collaborate with developers, project managers, content, marketing, and client-facing teams through discovery, design review, implementation, accessibility-focused design, and QA.');
bullet('Support company marketing and digital initiatives alongside client web work, using AI-assisted workflows to prototype, build, and maintain websites more efficiently.');
y+=5;line('UX/UI Designer | 8com Limited | 2023',10.2,true,12);line('Maidenhead, UK',9,false,11);bullet('Designed responsive websites, mobile apps, and dashboards for an agency serving clients across multiple industries.');bullet('Translated varied client requirements into user flows, wireframes, responsive interfaces, and polished visual systems while adapting to different brands, audiences, and product types.');
y+=5;line('Freelance Web & UI Designer | Upwork & Direct Clients | 2021 - Present',10.2,true,12);line('International | Remote',9,false,11);bullet('Delivered 10+ projects for clients across different countries and industries, starting with freelance graphic design in university and expanding into web and UI/UX design.');bullet('Own projects from early requirements through site structure, wireframes, visual direction, responsive UI, and implementation, tailoring each experience to the business and its audience.');bullet('Designed multilingual LTR/RTL websites, booking flows, travel-program experiences, service-business websites, and other digital interfaces; build and maintain selected websites in Framer.');
sec('CORE SKILLS');line('Web Design | Responsive UI | UI/UX Design | Information Architecture | Wireframing | Prototyping | Accessibility | Design Systems | Figma Variables | Basic HTML & CSS | LTR/RTL Design | Figma | Framer | AI-assisted Web Development | Website Maintenance | Graphic Design',9.3,false,11.2);
sec('EDUCATION');line('Bachelors in Product Design | Faculty of Applied Arts, Helwan University | 2022',9.7,true,12);
sec('CERTIFICATION');line('Advanced User Experience Design Nanodegree | Udacity',9.5,false,12);
d.save('Esraa_Salah_Web_Designer_CV.pdf')};
