const cards=[
['powergrid','PowerGrid Services','Scalable B2B system · 16 websites','A reusable website system designed to flex across 16 utility-infrastructure brands without turning them into 16 unrelated sites.','assets/images/POWERGRID.webp',['Design system','B2B','Code prototype']],
['dalton','Town of Dalton','Custom municipal · Massachusetts','An RFP / win-back project with three distinct directions, responsive page design and accessibility treated as a real design requirement.','assets/images/DALTON.webp',['Custom UX/UI','Accessibility','Responsive']],
['amenia','Town of Amenia','Custom municipal · New York','A fully custom municipal experience built around findability, resident self-service and accessible access to everyday town information.','assets/images/AMENIA.webp',['Municipal UX','Live','Responsive']],
['flatland','Flatland Roofing & Insulation','Service business · USA','A full website process from page names to sitemap, wireframes, final UI and stakeholder iteration.','assets/images/FLATLAND HOME PAGE.webp',['IA','Wireframes','UX/UI']],
['referral','ClerkMinutes Referral','Product UX · 2026','A gamified referral experience translating two incentive models into clear flows, progress states, rewards and completion feedback.','assets/images/REFERRAL.webp',['Product UX','Flows','States']],
['soheir','Soheir Farag Swimming Academy','Independent client · Egypt','A bilingual website I initiated, designed, built, launched and continue to maintain for a ladies-only swimming academy.','assets/images/SOHEIR FARAG EN.webp',['Framer','Arabic RTL','End to end']]
];
const archive=[
['Greenwood','Premier municipal','assets/images/GREENWOOD.webp'],['Neenah','Premier municipal','assets/images/GREENWOOD.webp'],['Millstone Township','Custom municipal','assets/images/AMENIA.webp'],['Cedarburg','Custom municipal','assets/images/DALTON.webp'],['Delavan','Custom municipal','assets/images/DALTON.webp'],['Garden City','Premier municipal','assets/images/GREENWOOD.webp'],['Millbrook','Premier municipal','assets/images/GREENWOOD.webp'],['Sandy Oaks','Premier municipal','assets/images/GREENWOOD.webp'],['Merton','Premier municipal','assets/images/GREENWOOD.webp'],['Barton','Premier municipal','assets/images/GREENWOOD.webp'],['Garfield','Upgrade municipal','assets/images/DALTON.webp'],['Complete Safety Concepts','External / B2B','assets/images/SAFETY.webp'],['Braga Brothers','External / B2B','assets/images/FLATLAND HOME PAGE.webp'],['180 Contractors','External / B2B','assets/images/FLATLAND HOME PAGE.webp'],['Clerkware','Brand + web concept','assets/images/CLERKWARE.webp']
];
const cases={
powergrid:{name:'PowerGrid Services',status:'In progress · 16-site scalable system',intro:'PowerGrid is a larger external engagement covering 16 family-company websites. I am the sole designer, building one reusable design system that can adapt to each company’s logo, typography, colors and imagery while keeping the underlying experience consistent.',notes:[['One system, many brands','The design has to feel native to each company without rebuilding the experience sixteen times. I created a shared visual and structural foundation that can change brand expression while preserving layout logic and usability.'],['Designed in the browser','The first homepage direction was built directly on staging with responsive desktop/mobile behavior and intended interactions. A live variation test switches between AMPP, CSR and James to prove the system rather than only describe it.'],['Design + feasibility','Working in staging lets the team experience the direction realistically and exposes implementation questions earlier. The project combines discovery, responsive UI, systems thinking and close design-to-development coordination.']],quote:'The goal is not sixteen websites that happen to look related. It is one strong system that can genuinely belong to sixteen companies.',images:[['Working design direction','assets/images/POWERGRID.webp']]},
dalton:{name:'Town of Dalton',status:'Custom municipal · RFP / win-back',intro:'Dalton is one of my strongest examples of end-to-end municipal ownership. I created three distinct design directions, then carried the selected approach through responsive homepage and department-page design, components, revisions and accessibility decisions.',notes:[['Three real directions','Instead of superficial variations, I explored three distinct directions that each responded to details the client had hinted at, giving the committee meaningful choices before refining the final system.'],['Accessibility from the start','Accessibility was one of the client’s priorities, so contrast, focus behavior, hierarchy and interaction clarity were part of the design logic rather than a checklist at handoff.'],['Client-facing ownership','The work moved through internal review, client reveal, revisions and committee approval, with responsive desktop, tablet and mobile states supporting the final direction.']],quote:'A high-stakes municipal project where concept, accessibility and client approval all had to work together.',images:[['Desktop homepage','assets/images/DALTON.webp'],['Mobile design','assets/images/DALTON MOBILE.webp','mobile']]},
amenia:{name:'Town of Amenia',status:'Live · Custom municipal UX',intro:'Amenia was a fully custom municipal project where I led the UX/UI direction. The work addressed real resident needs: findability, quick access to services, responsive behavior, accessibility, calendars, forms, permits, agendas, minutes and navigation.',notes:[['Resident-first structure','Municipal visitors rarely browse for fun. The experience prioritizes common tasks and self-service so residents can get to the right information without understanding the town’s internal structure.'],['A reusable reference point','After launch, Amenia became a reference direction for later clients who repeatedly asked for a similar look and experience.'],['Sole design ownership','I owned the UX/UI and visual design while collaborating with PMs, developers and the client through the project lifecycle.']],quote:'The visual refresh mattered, but the real job was making a municipal website easier to use.',images:[['Amenia case-study overview','assets/images/AMENIA.webp']],live:'https://ameniany.gov/'},
flatland:{name:'Flatland Roofing & Insulation',status:'External / B2B · Full website process',intro:'Flatland began with little more than the pages the client knew they wanted. I turned that into an approved sitemap, wireframes and a complete responsive website direction.',notes:[['Information architecture','I proposed how roofing, insulation, commercial services and supporting content should fit together before detailed design began.'],['Structure before polish','Internal-page wireframes let us align on hierarchy, content flow and conversion points before visual styling complicated the conversation.'],['Stakeholder iteration','The Figma history preserves the full path from sitemap and wireframes through homepage, internal pages and final stakeholder revisions.']],quote:'Page names became a real information architecture, then a complete conversion-focused interface.',images:[['Homepage','assets/images/FLATLAND HOME PAGE.webp'],['Proposed sitemap','assets/images/Flatland-sitemap (1)-1.webp'],['Internal wireframe','assets/images/FLATLAND INTERNAL PAGE WIREFRAME.webp'],['Final internal page','assets/images/FLATLAND INTERNAL PAGE.webp']]},
referral:{name:'ClerkMinutes Referral',status:'Product UX/UI · 2026',intro:'I designed a gamified referral experience for the ClerkMinutes dashboard, translating two different incentive models into clear flows and interface states for annual and monthly users.',notes:[['Two incentive models','Annual users work toward a physical reward while monthly users receive an ongoing referral benefit. The interface needed to explain both without making the dashboard feel like a separate product.'],['State design','The work covers progress, reward eligibility, time-based states, paid-conversion feedback, referral history, completion and retry states.'],['Product thinking','The challenge was less about decorating a widget and more about making rules, progress and rewards immediately understandable.']],quote:'A small dashboard surface with a surprisingly large amount of product logic underneath it.',images:[['Referral states','assets/images/REFERRAL.webp']]},
soheir:{name:'Soheir Farag Swimming Academy',status:'Live · Independent end-to-end',intro:'This project started before there was a client brief. I designed a homepage concept based on what I understood about the academy, showed the owner a working direction, then turned that idea into the complete live website.',notes:[['100% ownership','I found the client, initiated the project, recommended the structure, communicated directly with the owner, designed every page, built it in Framer, handled hosting and launched it. I still maintain it.'],['Bilingual by design','The English and Arabic versions are treated as real LTR and RTL experiences, with navigation, alignment and composition responding to reading direction.'],['A fitting brand','The direction is feminine without becoming childish, using aquatic color, clean layouts and sporty imagery to keep the academy credible and active.']],quote:'I did not wait for a brief. I showed the client a vision first, then turned it into the real business website.',images:[['English homepage','assets/images/SOHEIR FARAG EN.webp'],['Arabic RTL homepage','assets/images/SOHEIR FARAG ARABIC.webp']],live:'https://www.soheirfarag.com/'}
};
const P=document.getElementById('projects');cards.forEach((c,idx)=>{let e=document.createElement('article');e.className='project'+(idx===0?' feature':'');e.tabIndex=0;e.dataset.case=c[0];e.innerHTML=`<div class="visual"><img loading="${idx<2?'eager':'lazy'}" decoding="async" src="${c[4]}" alt="${c[1]} design"><span class="view">View case study</span></div><div class="copy"><div class="label">${c[2]}</div><h3>${c[1]}</h3><p>${c[3]}</p><div class="tags">${c[5].map(t=>`<span>${t}</span>`).join('')}</div></div>`;P.appendChild(e)});
const A=document.getElementById('archive');archive.forEach(a=>{let e=document.createElement('article');e.className='archive-card';e.innerHTML=`<div class="archive-img"><img loading="lazy" src="${a[2]}" alt="${a[0]} project"></div><div><strong>${a[0]}</strong><span>${a[1]}</span></div>`;A.appendChild(e)});
const M=document.getElementById('modal'),B=document.getElementById('case'),N=document.getElementById('modalName');function openCase(k){let c=cases[k];if(!c)return;N.textContent=c.name;let notes=c.notes.map(n=>`<div class="note"><h4>${n[0]}</h4><p>${n[1]}</p></div>`).join('');let g=c.images.map((x,i)=>`<div><div class="cap">${x[0]}</div><div class="shot ${x[2]==='mobile'?'mobile-shot':''}"><img loading="lazy" decoding="async" src="${x[1]}" alt="${c.name} ${x[0]}"></div>${i===0?`<div class="notes">${notes}</div><div class="quote">${c.quote}</div>`:''}</div>`).join('');B.innerHTML=`<div class="case-head"><div class="ey">${c.status}</div><h2>${c.name}</h2><p>${c.intro}</p></div><div class="gallery">${g}</div>${c.live?`<a class="live" href="${c.live}" target="_blank">View live website ↗</a>`:''}`;M.classList.add('open');document.body.classList.add('no-scroll');M.scrollTop=0}function shut(){M.classList.remove('open');document.body.classList.remove('no-scroll')}P.onclick=e=>{let x=e.target.closest('.project');if(x)openCase(x.dataset.case)};P.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.project'))openCase(e.target.closest('.project').dataset.case)};document.getElementById('close').onclick=shut;
const W=[['clear.','#0071e3'],['useful.','#7c3aed'],['beautiful.','#d05a2a'],['buildable.','#198754']];let i=0,w=document.getElementById('word');w.style.color=W[0][1];setInterval(()=>{w.style.opacity=0;w.style.transform='translateY(5px)';setTimeout(()=>{i=(i+1)%W.length;w.textContent=W[i][0];w.style.color=W[i][1];w.style.opacity=1;w.style.transform='none'},110)},950);
const CV=document.getElementById('cvModal');function cvShut(){CV.classList.remove('open');if(!M.classList.contains('open'))document.body.classList.remove('no-scroll')}document.getElementById('cvBtn').onclick=()=>{CV.classList.add('open');document.body.classList.add('no-scroll')};document.getElementById('cvClose').onclick=cvShut;document.addEventListener('keydown',e=>{if(e.key==='Escape'){shut();cvShut()}});
