
const cases={
powergrid:{k:"SCALABLE B2B WEB SYSTEM · 2026",title:"PowerGrid Services",intro:"A design system for 16 company websites, built to adapt to distinct brands without fragmenting the family into unrelated experiences.",imgs:["assets/images/v4/powergrid.png"],a:"The system problem",ap:"The direction had to accommodate different logos, typography, colors and imagery while preserving a coherent structure. The first variation was built directly on staging so responsive behavior and interactions could be tested early.",b:"My role",bp:"Sole designer across discovery, responsive UI, reusable system thinking, brand variation, interaction decisions and design-development coordination."},
dalton:{k:"CUSTOM MUNICIPAL · RFP / WIN-BACK",title:"Town of Dalton",intro:"Three distinct design directions, responsive home and department pages, components, revisions and accessibility-focused decisions for a high-stakes municipal project.",imgs:["assets/images/DALTON.webp","assets/images/DALTON MOBILE.webp"],a:"Why it mattered",ap:"The client had meaningful accessibility priorities, so accessibility shaped the design rather than appearing as a final checklist. The selected direction moved through client review to committee approval.",b:"My role",bp:"Sole designer. Client requirements, design direction, responsive UX/UI, accessibility decisions, components, revisions and implementation support."},
amenia:{k:"CUSTOM MUNICIPAL · LIVE",title:"Town of Amenia",intro:"A fully custom municipal experience focused on findability, quick access to services, responsive behavior, accessibility and resident self-service.",imgs:[],a:"The problem",ap:"Municipal websites carry dense information and recurring resident tasks. The work addressed navigation, calendars, forms and permits, agendas and minutes, and service access rather than treating the project as a visual refresh.",b:"What happened next",bp:"Amenia became a reference point for later clients who repeatedly asked for a similar design direction."},
flatland:{k:"COMMERCIAL / B2B · END TO END",title:"Flatland Roofing & Insulation",intro:"A complete commercial website process preserved from sitemap and wireframes through final UI and stakeholder iteration.",imgs:["assets/images/Flatland-sitemap (1)-1.webp","assets/images/FLATLAND INTERNAL PAGE WIREFRAME.webp","assets/images/FLATLAND HOME PAGE.webp","assets/images/FLATLAND INTERNAL PAGE.webp"],a:"Process",ap:"The project demonstrates the part of web design that happens before polished screens: structuring the site, defining page hierarchy, wireframing and then carrying that thinking into the visual system.",b:"My role",bp:"Sole designer working directly from the agreed client scope through sitemap, wireframes, homepage, internal pages and revisions."},
referral:{k:"PRODUCT UX/UI · 2026",title:"ClerkMinutes Referral",intro:"A gamified referral experience translating two incentive models into understandable user flows and interface states.",imgs:[],a:"UX complexity",ap:"The work includes referral progress, reward eligibility, time-based states, paid-conversion feedback, referral history and completion/reward states, with separate experiences for annual and monthly users.",b:"Why it belongs here",bp:"It shows product thinking beyond marketing surfaces: flows, state logic, feedback and interaction design."},
soheir:{k:"FREELANCE · BILINGUAL",title:"Soheir Farag",intro:"An independently owned bilingual website spanning English and Arabic, design, build and ongoing maintenance.",imgs:["assets/images/SOHEIR FARAG EN.webp","assets/images/SOHEIR FARAG ARABIC.webp"],a:"Ownership",ap:"A useful counterpoint to larger team projects: one designer carrying the experience from requirements through responsive UI and implementation.",b:"Range",bp:"The Arabic version adds RTL considerations while keeping the visual system coherent across languages."}
};
const modal=document.getElementById("caseModal"),content=document.getElementById("caseContent");
function openCase(key){const c=cases[key];if(!c)return;content.innerHTML=`<div class="case-inner"><div class="kicker">${c.k}</div><h1>${c.title}</h1><p class="intro">${c.intro}</p>${c.imgs.map(x=>`<img src="${x}" alt="">`).join("")}<div class="case-grid"><div><h2>${c.a}</h2><p>${c.ap}</p></div><div><h2>${c.b}</h2><p>${c.bp}</p></div></div></div>`;modal.classList.add("open");document.body.style.overflow="hidden"}
document.querySelectorAll("[data-project]").forEach(x=>x.addEventListener("click",()=>openCase(x.dataset.project)));
document.getElementById("caseClose").onclick=()=>{modal.classList.remove("open");document.body.style.overflow=""};
const details={
product:["Product UX/UI","Referral flows, reward logic, interaction states and the original Command Center experience show product thinking beyond websites.","product"],
brand:["Municipal identity","Custom identity work translates local history, landscape and community character into visual systems municipalities could actually use.","brand"],
campaign:["Campaign design","Ongoing print and digital work across postcards, flyers, conference collateral, landing pages and campaign concepts.","campaign"]
};
const galleries={
product:{title:"Product UX/UI",copy:"Selected product work including the ClerkMinutes referral experience and an earlier unified municipal-clerk product concept.",imgs:["assets/images/v4/referral.png","assets/images/v4/clerkware.png"]},
brand:{title:"Brand design",copy:"A sample of paid municipal identity work across very different communities and visual directions.",imgs:["assets/images/v4/logos.jpg"]},
campaign:{title:"Campaign design",copy:"A selection from ongoing marketing work across print and digital formats.",imgs:["assets/images/v4/campaigns.png"]}
};
document.querySelectorAll(".range-panel").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".range-panel").forEach(b=>b.classList.remove("active"));btn.classList.add("active");const d=details[btn.dataset.panel],box=document.getElementById("rangeDetail");box.innerHTML=`<div><h3>${d[0]}</h3><p>${d[1]}</p></div><button data-gallery="${d[2]}">View selected work ↗</button>`;box.classList.add("open");box.querySelector("button").onclick=()=>openGallery(d[2])}));
const cv=document.getElementById("cvModal"),cvBtn=document.getElementById("cvBtn"),cvClose=document.getElementById("cvClose");
if(cvBtn&&cv){cvBtn.onclick=()=>{cv.classList.add("open");document.body.style.overflow="hidden"}}
if(cvClose&&cv){cvClose.onclick=()=>{cv.classList.remove("open");document.body.style.overflow=""}}
const media=document.querySelector(".feature-media img");
window.addEventListener("scroll",()=>{if(media){const r=media.parentElement.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)media.style.transform=`scale(1.03) translateY(${r.top*.025}px)`}},{passive:true});

const galleryModal=document.getElementById("galleryModal"),galleryContent=document.getElementById("galleryContent");
function openGallery(key){const g=galleries[key];galleryContent.innerHTML=`<span>SELECTED WORK</span><h2>${g.title}</h2><p>${g.copy}</p><div class="gallery-images">${g.imgs.map(x=>`<img src="${x}" alt="">`).join("")}</div>`;galleryModal.classList.add("open");document.body.style.overflow="hidden"}
document.getElementById("galleryClose").onclick=()=>{galleryModal.classList.remove("open");document.body.style.overflow=""};
